# Generated by Django 2.0.13 on 2020-11-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userEmail', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('userPassWord', models.CharField(max_length=200)),
                ('userName', models.CharField(max_length=100)),
                ('userAge', models.IntegerField()),
                ('userInterest', models.CharField(max_length=200)),
            ],
        ),
    ]
