# Generated by Django 2.0.13 on 2020-11-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userPassWord',
            new_name='userPassword',
        ),
    ]
