# Generated by Django 2.0.13 on 2020-11-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201105_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userCreated',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='userLike',
            field=models.TextField(default=''),
        ),
    ]
