# Generated by Django 2.0.13 on 2020-11-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201107_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userCode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='userSex',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
