# Generated by Django 2.0.13 on 2020-12-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201114_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userPaid',
            field=models.IntegerField(default=0),
        ),
    ]
