# Generated by Django 2.0.13 on 2020-12-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_userpaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userPaidEndDate',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
