# Generated by Django 2.0.13 on 2020-11-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('galleryTitle', models.CharField(max_length=100)),
                ('galleryCreator', models.CharField(default='', max_length=30)),
                ('galleryInfo', models.CharField(default='', max_length=300)),
                ('galleryCode', models.IntegerField(db_index=True, default=-1, primary_key=True, serialize=False, unique=True)),
                ('titles', models.TextField(default='')),
                ('contents', models.TextField(default='')),
            ],
        ),
    ]
