# Generated by Django 2.0.13 on 2020-11-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='galleryAmount',
            field=models.IntegerField(default=0),
        ),
    ]
