# Generated by Django 2.0.13 on 2020-11-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_exhibition_galleryamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='category',
            field=models.CharField(default='000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='dueDate',
            field=models.CharField(default='20000000', max_length=8),
        ),
    ]
