# Generated by Django 2.0.13 on 2020-11-09 15:31

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_exhibition_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imagekit.models.fields.ProcessedImageField(null=True, upload_to='test')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Exhibition')),
            ],
        ),
    ]
