# Generated by Django 2.0.13 on 2020-11-09 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='exhibition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Exhibition'),
        ),
    ]
