# Generated by Django 2.0.13 on 2020-11-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20201110_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='images',
            name='exhibition',
        ),
    ]
