# Generated by Django 2.0.13 on 2020-11-12 03:59

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_remove_exhibition_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='temp'),
        ),
    ]
