# Generated by Django 2.0.13 on 2020-11-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='newPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auction',
            name='startPrice',
            field=models.IntegerField(default=0),
        ),
    ]
