# Generated by Django 2.0.13 on 2020-11-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_auto_20201117_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='id',
        ),
        migrations.AddField(
            model_name='auction',
            name='artistEmail',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='auction',
            name='auctionCode',
            field=models.IntegerField(db_index=True, default=-1, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='auctionState',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auction',
            name='buyerEmail',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='auction',
            name='endDate',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AddField(
            model_name='auction',
            name='startDate',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='auctionStates',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='galleryLikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='galleryViews',
            field=models.IntegerField(default=0),
        ),
    ]
