# Generated by Django 2.0.13 on 2020-11-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_auto_20201117_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='shortInfo',
            field=models.CharField(default='', max_length=300),
        ),
    ]
