# Generated by Django 2.0.13 on 2020-11-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_exhibition_shortinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='shortInfo',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
